# Generated by Django 2.1.11 on 2019-08-20 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=50)),
                ('book_isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('book_copys', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='books_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('book_fine', models.IntegerField()),
                ('issued_book', models.OneToOneField(on_delete=False, to='management.books')),
                ('user', models.OneToOneField(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
