# Generated by Django 2.1.11 on 2019-08-28 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_transactions',
            name='issued_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.books'),
        ),
        migrations.AlterField(
            model_name='books_transactions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
